services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: pavel
      RABBITMQ_DEFAULT_PASS: popov
    networks:
      - backend

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: pavel
      MONGO_INITDB_ROOT_PASSWORD: popov
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    depends_on:
      - rabbitmq
    networks:
      - backend

  controller:
    image: highload-2025-controller:latest
    volumes:
      - controller_src:/controller/src
      - logs_storage:/var/log/
    depends_on:
      - mongo
      - redis
      - rabbitmq
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 512M
      restart_policy:
        condition: on-failure
    networks:
      - backend

  rule_engine:
    image: highload-2025-rule_engine:latest
    volumes:
      - rule_engine_src:/rule_engine/src
      - logs_storage:/var/log/
    ports:
      - "8700:8700"
    depends_on:
      - controller
      - mongo
      - redis
      - rabbitmq
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 512M
      restart_policy:
        condition: on-failure
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  filebeat:
    image: elastic/filebeat:8.15.3
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - logs_storage:/var/log
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html
    networks:
      - backend

volumes:
  mongo_data:
  rabbitmq_data:
  controller_src:
  rule_engine_src:
  grafana_storage:
  prometheus_data:
  logs_storage:

networks:
  backend:
    driver: overlay
