services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: pavel
      RABBITMQ_DEFAULT_PASS: popov
    networks:
      - backend

  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    command: [ "--replSet", "rs0",
               "--auth",
               "--keyFile", "/etc/mongo-keyfile", "--bind_ip_all" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: pavel
      MONGO_INITDB_ROOT_PASSWORD: popov
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
      - mongo_data:/data/db
    networks:
      - backend

  mongo_replica:
    image: mongo:6
    ports:
      - '27018:27017'
    command: [ "--replSet", "rs0",
               "--auth",
               "--keyFile", "/etc/mongo-keyfile",
               "--bind_ip_all" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: pavel
      MONGO_INITDB_ROOT_PASSWORD: popov

    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
      - mongo_replica:/data/db
    networks:
      - backend

  mongo_arbiter:
    image: mongo:6
    command: [ "--replSet", "rs0", "--auth",
              "--keyFile", "/etc/mongo-keyfile",
               "--bind_ip_all" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: pavel
      MONGO_INITDB_ROOT_PASSWORD: popov
    ports:
      - '27019:27017'
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
    networks:
      - backend

#  configsvr:
#    image: mongo:6
#    command: [ "--configsvr", "--replSet", "--port", "27017" ,"cfg", "--auth", "--keyFile", "/etc/mongo-keyfile", "--bind_ip_all" ]
#    volumes:
#      - ./mongo-keyfile:/etc/mongo-keyfile:ro
#      - config_data:/data/configdb
#    networks:
#      - backend

#  mongos:
#    image: mongo:6
#    ports:
#      - "27020:27017"
#    depends_on:
#      - configsvr
#      - mongo
#    command: >
#      mongos --configdb cfg/configsvr:27017 --keyFile /etc/mongo-keyfile --bind_ip_all
#    volumes:
#      - ./mongo-keyfile:/etc/mongo-keyfile:ro
#    networks:
#      - backend

  init-mongo:
    image: mongo:6
    volumes:
      - ./init-replica.sh:/init-replica.sh
    networks:
      - backend
    depends_on:
      - mongo
      - mongo_replica
      - mongo_arbiter
    entrypoint:
      - bash
      - -c
      - |
        sleep 7
        mongosh --host mongo:27017 -u pavel -p popov --authenticationDatabase admin <<EOF
        rs.initiate({
          _id: "rs0",
          members: [
            { _id: 0, host: "mongo:27017" },
            { _id: 1, host: "mongo_replica:27017" },
            { _id: 2, host: "mongo_arbiter:27017", arbiterOnly: true }
          ]
        })
        EOF

    deploy:
      restart_policy:
        condition: none

  controller:
    build:
      context: ./controller
    restart: on-failure
    volumes:
      - controller_src:/controller/src
      - logs_storage:/var/log/
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .
    depends_on:
      - mongo
      - mongo_replica
      - redis
      - rabbitmq
    networks:
      - backend

  rule_engine:
    build:
      context: ./rule_engine
    restart: on-failure
    volumes:
      - rule_engine_src:/rule_engine/src
      - logs_storage:/var/log/
    ports:
      - "8700:8700"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .
    depends_on:
      - controller
      - mongo
      - mongo_replica
      - redis
      - rabbitmq
    networks:
      - backend

  datasim:
    build:
      context: ./datasim
    restart: always
    volumes:
      - datasim_src:/datasim/src
      - logs_storage:/var/log/
    ports:
      - "8070:8070"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .
    depends_on:
      - rule_engine
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

#  tsung:
#    build:
#      context: ./tsung
#    restart: on-failure
#    volumes:
#      - tsung_src:/tsung/scenarios
#    develop:
#      watch:
#        - action: sync+restart
#          path: .
#          target: .


#  elasticsearch:
#    image: elasticsearch:8.15.3
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#    ports:
#      - "9200:9200"
#    restart: on-failure
#    networks:
#      - backend
#
#  logstash:
#    image: logstash:8.15.3
#    ports:
#      - "5044:5044"
#      - "9600:9600"
#    volumes:
#      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#    networks:
#      - backend
#    restart: on-failure
#    depends_on:
#      - elasticsearch
#
#  kibana:
#    image: kibana:8.15.3
#    ports:
#      - "5601:5601"
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    networks:
#      - backend
#    restart: on-failure
#    depends_on:
#      - elasticsearch

  filebeat:
    image: elastic/filebeat:8.15.3
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - logs_storage:/var/log
    networks:
      - backend
    restart: on-failure

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html
    restart: on-failure
    networks:
      - backend

volumes:
  mongo_data:
  config_data:
  mongo_replica:
  rabbitmq_data:
  controller_src:
  datasim_src:
#  tsung_src:
  rule_engine_src:
  grafana_storage:
  prometheus_data:
  logs_storage:

networks:
  backend:
    driver: bridge
