services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: pavel
      RABBITMQ_DEFAULT_PASS: popov
    networks:
      - backend

  mongo_rs1_primary:
    image: mongo:6
    command: [ "--replSet", "rs1", "--bind_ip_all", "--shardsvr", "--port", "27017" ]
    networks:
      - backend

  mongo_rs1_secondary:
    image: mongo:6
    command: [ "--replSet", "rs1",
               "--bind_ip_all", "--shardsvr", "--port", "27017" ]
    networks:
      - backend

  mongo_rs1_tertiary:
    image: mongo:6
    command: [ "--replSet", "rs1",
               "--bind_ip_all", "--shardsvr", "--port", "27017" ]
    networks:
      - backend

  mongo_rs2_primary:
    image: mongo:6
    command: [ "--replSet", "rs2", "--bind_ip_all", "--shardsvr", "--port", "27017" ]
    networks:
      - backend

  mongo_rs2_secondary:
    image: mongo:6
    command: [ "--replSet", "rs2", "--bind_ip_all", "--shardsvr", "--port", "27017" ]
    networks:
      - backend

  mongo_rs2_tertiary:
    image: mongo:6
    command: [ "--replSet", "rs2",
               "--bind_ip_all", "--shardsvr", "--port", "27017" ]
    networks:
      - backend

  mongo_config1:
    image: mongo:6
    command: [ "--replSet", "configReplSet", "--configsvr", "--bind_ip_all", "--port", "27017" ]
    networks:
      - backend

  mongo_config2:
    image: mongo:6
    command: [ "--replSet", "configReplSet", "--configsvr", "--bind_ip_all", "--port", "27017" ]
    networks:
      - backend

  mongo_config3:
    image: mongo:6
    command: [ "--replSet", "configReplSet", "--configsvr", "--bind_ip_all", "--port", "27017" ]
    networks:
      - backend

  mongos:
    image: mongo:6
    command: >
      mongos --configdb configReplSet/mongo_config1:27017,mongo_config2:27017,mongo_config3:27017 --port 27017 "--bind_ip_all"
    depends_on:
      - mongo_config1
      - mongo_config2
      - mongo_config3
    ports:
      - '27022:27017'
    networks:
      - backend

  init-sharding:
    image: mongo:6
    depends_on:
      - mongo_config1
      - mongo_config2
      - mongo_config3
      - init-replicasets
      - mongos
    networks:
      - backend
    entrypoint:
      - bash
      - -c
      - |
        sleep 20
        echo "Initializing config replica set..."
        mongosh --host mongo_config1:27017 <<EOF
        rs.initiate({
          _id: "configReplSet",
          configsvr: true,
          members: [
            { _id: 0, host: "mongo_config1:27017" },
            { _id: 1, host: "mongo_config2:27017" },
            { _id: 2, host: "mongo_config3:27017" }
          ]
        })
        EOF

        until [ "$(mongosh --quiet --host mongo_config1:27017 --eval 'print(rs.isMaster().ismaster)')" = "true" ]
        do
          echo "Still waiting for PRIMARY..."
          sleep 2
        done
        echo "PRIMARY is ready."


        sleep 5
        echo "Adding shards..."
        mongosh --host mongos:27017 <<EOF
        sh.addShard("rs1/mongo_rs1_primary:27017,mongo_rs1_secondary:27017,mongo_rs1_tertiary:27017")
        sh.addShard("rs2/mongo_rs2_primary:27017,mongo_rs2_secondary:27017,mongo_rs2_tertiary:27017")
        sh.enableSharding("iotdata")
        sh.shardCollection("iotdata.data", { _id: 1})
        EOF

  init-replicasets:
    image: mongo:6
    networks:
      - backend
    depends_on:
      - mongo_rs1_primary
      - mongo_rs1_secondary
      - mongo_rs1_tertiary
      - mongo_rs2_primary
      - mongo_rs2_secondary
      - mongo_rs2_tertiary
    entrypoint:
      - bash
      - -c
      - |
        sleep 10
        mongosh --host mongo_rs1_primary:27017 <<EOF
        rs.initiate({
          _id: "rs1",
          members: [
            { _id: 0, host: "mongo_rs1_primary:27017" },
            { _id: 1, host: "mongo_rs1_secondary:27017" },
            { _id: 2, host: "mongo_rs1_tertiary:27017" }
          ]
        })
        EOF

        mongosh --host mongo_rs2_primary:27017 <<EOF
        rs.initiate({
          _id: "rs2",
          members: [
            { _id: 0, host: "mongo_rs2_primary:27017" },
            { _id: 1, host: "mongo_rs2_secondary:27017" },
            { _id: 2, host: "mongo_rs2_tertiary:27017"}
          ]
        })
        EOF

  controller:
    build:
      context: ./controller
    restart: on-failure
    volumes:
      - controller_src:/controller/src
      - logs_storage:/var/log/
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .
    depends_on:
      - redis
      - rabbitmq
      - init-sharding
    networks:
      - backend

  rule_engine:
    build:
      context: ./rule_engine
    restart: on-failure
    volumes:
      - rule_engine_src:/rule_engine/src
      - logs_storage:/var/log/
    ports:
      - "8700:8700"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .
    depends_on:
      - controller
      - redis
      - rabbitmq
      - init-sharding
    networks:
      - backend

  datasim:
    build:
      context: ./datasim
    restart: always
    volumes:
      - datasim_src:/datasim/src
      - logs_storage:/var/log/
    ports:
      - "8070:8070"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .
    depends_on:
      - rule_engine
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  tsung:
    build:
      context: ./tsung
    restart: on-failure
    volumes:
      - tsung_src:/tsung/scenarios
    develop:
      watch:
        - action: sync+restart
          path: .
          target: .


#  elasticsearch:
#    image: elasticsearch:8.15.3
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#    ports:
#      - "9200:9200"
#    restart: on-failure
#    networks:
#      - backend
#
#  logstash:
#    image: logstash:8.15.3
#    ports:
#      - "5044:5044"
#      - "9600:9600"
#    volumes:
#      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#    networks:
#      - backend
#    restart: on-failure
#    depends_on:
#      - elasticsearch
#
#  kibana:
#    image: kibana:8.15.3
#    ports:
#      - "5601:5601"
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    networks:
#      - backend
#    restart: on-failure
#    depends_on:
#      - elasticsearch

  filebeat:
    image: elastic/filebeat:8.15.3
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - logs_storage:/var/log
    networks:
      - backend
    restart: on-failure

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html
    restart: on-failure
    networks:
      - backend

volumes:
  config_data:
  rabbitmq_data:
  controller_src:
  datasim_src:
  tsung_src:
  rule_engine_src:
  grafana_storage:
  prometheus_data:
  logs_storage:

networks:
  backend:
    driver: bridge
