global:
  scrape_interval: 3s
scrape_configs:
  - job_name: controller
    dns_sd_configs:
      - names:
          - 'tasks.controller'
        type: 'A'
        port: 8060
  - job_name: rule_engine
    dns_sd_configs:
      - names:
          - 'tasks.rule_engine'
        type: 'A'
        port: 8080