name: highload-2025-ci

on:
  push:
    branches:
      - "467160"
  pull_request:
    branches:
      - "467160"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: docker compose build

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install Poetry via pip
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          cd controller && poetry install
          cd ../rule_engine && poetry install

      - name: Run Unit tests
        env:
          PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
        run: |
          cd controller && poetry run pytest
          cd ../rule_engine && poetry run pytest

      - name: Run Containers for integration tests
        run: |
          docker compose up -d controller
          docker compose up -d rule_engine
          docker compose logs -f &