name: highload-2025-ci

on:
  push:
    branches:
      - "467160"
  pull_request:
    branches:
      - "467160"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: docker compose build

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install Poetry via pip
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          cd controller && poetry install
          cd ../rule_engine && poetry install

      - name: Run Unit tests
        env:
          PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
        run: |
          cd controller && poetry run pytest -m unit
          cd ../rule_engine && poetry run pytest -m unit

      - name: Integration tests
        env:
          PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
        run: |
          docker compose up -d controller
          docker compose up -d rule_engine
          docker compose logs -f &
          
          cd controller && poetry run pytest -m integration
          cd ../rule_engine && poetry run pytest -m integration

      - name: Install tsung
        run: |
          sudo apt install tsung

      #--------------------------------------------------------

      - name: Load tests -- Many clients, Few requests
        run: |
          TSUNG_OUTPUT=$(tsung -f ./tsung/many-clients-few-requests.xml start)
          echo "$TSUNG_OUTPUT"

          TSUNG_LOG_DIR=$(echo "$TSUNG_OUTPUT" | grep 'Log directory is:' | awk -F': ' '{print $2}')
          echo "TSUNG_LOG_DIR=$TSUNG_LOG_DIR" >> $GITHUB_ENV
          echo "Tsung log directory: $TSUNG_LOG_DIR"

      - name: Archive Tsung logs -- Many clients, Few requests
        run: |
          mkdir -p reports
          cp -r "$TSUNG_LOG_DIR" reports/tsung-many-clients-few-requests-logs

      - name: Upload Tsung logs as artifact -- Many clients, Few requests
        uses: actions/upload-artifact@v4
        with:
          name: tsung-many-clients-few-requests-logs
          path: reports/tsung-many-clients-few-requests-logs

      #--------------------------------------------------------

      - name: Load tests -- Many requests, Few clients
        run: |
          TSUNG_OUTPUT=$(tsung -f ./tsung/many-requests-few-clients.xml start)
          echo "$TSUNG_OUTPUT"

          TSUNG_LOG_DIR=$(echo "$TSUNG_OUTPUT" | grep 'Log directory is:' | awk -F': ' '{print $2}')
          echo "TSUNG_LOG_DIR=$TSUNG_LOG_DIR" >> $GITHUB_ENV
          echo "Tsung log directory: $TSUNG_LOG_DIR"

      - name: Archive Tsung logs -- Many requests, Few clients
        run: |
          mkdir -p reports
          cp -r "$TSUNG_LOG_DIR" reports/tsung-many-requests-few-clients-logs

      - name: Upload Tsung logs as artifact -- Many requests, Few clients
        uses: actions/upload-artifact@v4
        with:
          name: tsung-many-requests-few-clients-logs
          path: reports/tsung-many-requests-few-clients-logs

      #--------------------------------------------------------

      - name: Load tests -- Many clients, Many requests
        run: |
          TSUNG_OUTPUT=$(tsung -f ./tsung/many-clients-many-requests.xml start)
          echo "$TSUNG_OUTPUT"

          TSUNG_LOG_DIR=$(echo "$TSUNG_OUTPUT" | grep 'Log directory is:' | awk -F': ' '{print $2}')
          echo "TSUNG_LOG_DIR=$TSUNG_LOG_DIR" >> $GITHUB_ENV
          echo "Tsung log directory: $TSUNG_LOG_DIR"

      - name: Archive Tsung logs -- Many clients, Many requests
        run: |
          mkdir -p reports
          cp -r "$TSUNG_LOG_DIR" reports/tsung-many-clients-many-requests-logs

      - name: Upload Tsung logs as artifact -- Many clients, Many requests
        uses: actions/upload-artifact@v4
        with:
          name: tsung-many-clients-many-requests-logs
          path: reports/tsung-many-clients-many-requests-logs

  publish:
    name: publish
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Docker tag
        id: vars
        run: echo "TAG=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build controller
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/controller:${{ env.TAG }} ./controller

      - name: Build rule engine
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rule_engine:${{ env.TAG }} ./rule_engine

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push controller
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/controller:${{ env.TAG }}

      - name: Push rule_engine
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rule_engine:${{ env.TAG }}
